# Generated by Django 5.2.1 on 2025-06-01 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('permissao', models.CharField(choices=[('Total', 'Total'), ('Parcial', 'Parcial')], max_length=10)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Clínica', 'Clínica'), ('Hospital', 'Hospital'), ('Home Care', 'Home Care'), ('Laboratório', 'Laboratório')], max_length=20)),
                ('cidade', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'unidade_saude',
            },
        ),
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('acao', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acesso', to='core.administrador')),
            ],
            options={
                'db_table': 'registro_acesso',
            },
        ),
    ]
