# Generated by Django 4.2.7 on 2025-06-04 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AddField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(default=-3, on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Django'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='permissao',
            field=models.CharField(choices=[('Total', 'Total'), ('Parcial', 'Parcial')], default='Parcial', max_length=10, verbose_name='Permissão'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
