# Generated by Django 5.2.2 on 2025-06-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
