# Generated by Django 5.2.2 on 2025-06-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_prontuario_data_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='tipo',
            field=models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial')], default='Presencial', max_length=20),
        ),
    ]
