# Generated by Django 4.2.7 on 2025-06-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='dosagem',
            field=models.PositiveIntegerField(max_length=50),
        ),
    ]
