# Generated by Django 5.2.1 on 2025-06-02 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('especialidade', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('crm_coren', models.CharField(max_length=20)),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='core.unidadesaude')),
            ],
            options={
                'db_table': 'profissional',
            },
        ),
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoLeito', models.CharField(choices=[('Enfermaria', 'Enfermaria'), ('UTI', 'UTI'), ('Isolamento', 'Isolamento')], max_length=20)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Ocupado', 'Ocupado'), ('Manutenção', 'Manutenção')], max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitos', to='core.unidadesaude')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitos', to='profissionais.profissional')),
            ],
            options={
                'db_table': 'leito',
            },
        ),
        migrations.CreateModel(
            name='Internacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('diagnostico', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internacoes', to='pacientes.paciente')),
                ('leito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internacoes', to='profissionais.leito')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internacoes', to='profissionais.profissional')),
            ],
            options={
                'db_table': 'internacao',
            },
        ),
    ]
