# Generated by Django 5.2.2 on 2025-06-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacesso',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
