# Generated by Django 5.2.1 on 2025-06-01 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('acao', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acesso_core', to='core.administrador')),
            ],
            options={
                'db_table': 'registro_acesso_admin',
            },
        ),
        migrations.CreateModel(
            name='RelatorioFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_registro', models.DateTimeField()),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_financeiros', to='core.unidadesaude')),
            ],
            options={
                'db_table': 'relatorio_financeiro',
            },
        ),
        migrations.CreateModel(
            name='Suprimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('validade', models.DateField()),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadesaude')),
            ],
            options={
                'db_table': 'suprimento',
            },
        ),
    ]
