# Generated by Django 4.2.7 on 2025-06-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suprimento',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
