# Generated by Django 5.2.2 on 2025-06-09 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(default='000.000.000-00', max_length=14)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=10)),
                ('data_nascimento', models.DateField(default='DD/MM/AAAA')),
                ('cidade', models.CharField(default='Cidade - EE', max_length=255)),
                ('cep', models.CharField(default='00.000-000', max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(default='(XX) XXXXX-XXXX', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='core.unidadesaude')),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
    ]
