# Generated by Django 5.2.2 on 2025-06-09 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Clínica', 'Clínica'), ('Hospital', 'Hospital'), ('Home Care', 'Home Care'), ('Laboratório', 'Laboratório')], max_length=20)),
                ('cidade', models.CharField(default='Cidade - EE', max_length=255)),
                ('cep', models.CharField(default='XX.XXX-XXX', max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(default='(XX) XXXXX-XXXX', max_length=15)),
            ],
            options={
                'db_table': 'unidade_saude',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('telefone', models.CharField(default='(XX) XXXXX-XXXX', max_length=15)),
                ('permissao', models.CharField(choices=[('Total', 'Total'), ('Parcial', 'Parcial')], default='Parcial', max_length=10, verbose_name='Permissão')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Django')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('acao', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acesso', to='core.administrador')),
            ],
            options={
                'db_table': 'registro_acesso',
            },
        ),
    ]
